const TILE_TYPES = {
  0: { name: 'algae green', src: '/assets/tiles/algae_green.png' },
  1: { name: 'basalt', src: '/assets/tiles/basalt.png' },
  2: { name: 'cave coral black weakened', src: '/assets/tiles/cave_coral_black_weakened.png' },
  3: { name: 'cave coral black', src: '/assets/tiles/cave_coral_black.png' },
  4: { name: 'cave gravel 2', src: '/assets/tiles/cave_gravel_2.png' },
  5: { name: 'cave gravel 3', src: '/assets/tiles/cave_gravel_3.png' },
  6: { name: 'cave gravel 4', src: '/assets/tiles/cave_gravel_4.png' },
  7: { name: 'cave gravel 5', src: '/assets/tiles/cave_gravel_5.png' },
  8: { name: 'cave gravel pit 1', src: '/assets/tiles/cave_gravel_pit_1.png' },
  9: { name: 'cave gravel pit 2', src: '/assets/tiles/cave_gravel_pit_2.png' },
  10: { name: 'cave gravel pit 3', src: '/assets/tiles/cave_gravel_pit_3.png' },
  11: { name: 'cave gravel', src: '/assets/tiles/cave_gravel.png' },
  12: { name: 'cave ice', src: '/assets/tiles/cave_ice.png' },
  13: { name: 'cave magma cold', src: '/assets/tiles/cave_magma_cold.png' },
  14: { name: 'cave magma', src: '/assets/tiles/cave_magma.png' },
  15: { name: 'cave wall', src: '/assets/tiles/cave_wall.png' },
  16: { name: 'cave water stalagmite', src: '/assets/tiles/cave_water_stalagmite.png' },
  17: { name: 'caveCliff2', src: '/assets/tiles/caveCliff2.png' },
  18: { name: 'caveCliff3', src: '/assets/tiles/caveCliff3.png' },
  19: { name: 'caveCliff4', src: '/assets/tiles/caveCliff4.png' },
  20: { name: 'caveCliff5', src: '/assets/tiles/caveCliff5.png' },
  21: { name: 'cavewater', src: '/assets/tiles/cavewater.png' },
  22: { name: 'clay', src: '/assets/tiles/clay.png' },
  23: { name: 'cliff ice', src: '/assets/tiles/cliff_ice.png' },
  24: { name: 'cliff', src: '/assets/tiles/cliff.png' },
  25: { name: 'coldCaveGravel', src: '/assets/tiles/coldCaveGravel.png' },
  26: { name: 'coldcliff', src: '/assets/tiles/coldcliff.png' },
  27: { name: 'construction path snowy', src: '/assets/tiles/construction_path_snowy.png' },
  28: { name: 'construction path', src: '/assets/tiles/construction_path.png' },
  29: { name: 'coral black weakened', src: '/assets/tiles/coral_black_weakened.png' },
  30: { name: 'coral black', src: '/assets/tiles/coral_black.png' },
  31: { name: 'coral blue chars', src: '/assets/tiles/coral_blue_chars.png' },
  32: { name: 'coral blue', src: '/assets/tiles/coral_blue.png' },
  33: { name: 'coral orange', src: '/assets/tiles/coral_orange.png' },
  34: { name: 'coralgreen', src: '/assets/tiles/coralgreen.png' },
  35: { name: 'coralred', src: '/assets/tiles/coralred.png' },
  36: { name: 'coralyellow', src: '/assets/tiles/coralyellow.png' },
  37: { name: 'cyan grass', src: '/assets/tiles/cyan_grass.png' },
  38: { name: 'darkCaveGravel', src: '/assets/tiles/darkCaveGravel.png' },
  39: { name: 'darkcliff', src: '/assets/tiles/darkcliff.png' },
  40: { name: 'deepocean', src: '/assets/tiles/deepocean.png' },
  41: { name: 'dryland', src: '/assets/tiles/dryland.png' },
  42: { name: 'dustgrass', src: '/assets/tiles/dustgrass.png' },
  43: { name: 'dustland', src: '/assets/tiles/dustland.png' },
  44: { name: 'farmland', src: '/assets/tiles/farmland.png' },
  45: { name: 'granite cliff', src: '/assets/tiles/granite_cliff.png' },
  46: { name: 'granite floor', src: '/assets/tiles/granite_floor.png' },
  47: { name: 'granite tile', src: '/assets/tiles/granite_tile.png' },
  48: { name: 'grass cold', src: '/assets/tiles/grass_cold.png' },
  49: { name: 'grass dry', src: '/assets/tiles/grass_dry.png' },
  50: { name: 'grass nov', src: '/assets/tiles/grass_nov.png' },
  51: { name: 'grass oct', src: '/assets/tiles/grass_oct.png' },
  52: { name: 'grass sep', src: '/assets/tiles/grass_sep.png' },
  53: { name: 'grass snowy', src: '/assets/tiles/grass_snowy.png' },
  54: { name: 'grass', src: '/assets/tiles/grass.png' },
  55: { name: 'gravel', src: '/assets/tiles/gravel.png' },
  56: { name: 'higherland', src: '/assets/tiles/higherland.png' },
  57: { name: 'highland arid', src: '/assets/tiles/highland_arid.png' },
  58: { name: 'highland snowy', src: '/assets/tiles/highland_snowy.png' },
  59: { name: 'highland', src: '/assets/tiles/highland.png' },
  60: { name: 'ice', src: '/assets/tiles/ice.png' },
  61: { name: 'infested gravel', src: '/assets/tiles/infested_gravel.png' },
  62: { name: 'junglegrass', src: '/assets/tiles/junglegrass.png' },
  63: { name: 'landcoralblack', src: '/assets/tiles/landcoralblack.png' },
  64: { name: 'lilypad', src: '/assets/tiles/lilypad.png' },
  65: { name: 'map tile city', src: '/assets/tiles/map_tile_city.png' },
  66: { name: 'map tile forest', src: '/assets/tiles/map_tile_forest.png' },
  67: { name: 'map tile grass', src: '/assets/tiles/map_tile_grass.png' },
  68: { name: 'map tile mountain', src: '/assets/tiles/map_tile_mountain.png' },
  69: { name: 'map tile ocean', src: '/assets/tiles/map_tile_ocean.png' },
  70: { name: 'map tile sand', src: '/assets/tiles/map_tile_sand.png' },
  71: { name: 'monsoongrass', src: '/assets/tiles/monsoongrass.png' },
  72: { name: 'mountainfloor', src: '/assets/tiles/mountainfloor.png' },
  73: { name: 'mud', src: '/assets/tiles/mud.png' },
  74: { name: 'ocean', src: '/assets/tiles/ocean.png' },
  75: { name: 'path snowy', src: '/assets/tiles/path_snowy.png' },
  76: { name: 'path', src: '/assets/tiles/path.png' },
  77: { name: 'path2 snowy', src: '/assets/tiles/path2_snowy.png' },
  78: { name: 'path2', src: '/assets/tiles/path2.png' },
  79: { name: 'pebbles cave', src: '/assets/tiles/pebbles_cave.png' },
  80: { name: 'pebbles snow', src: '/assets/tiles/pebbles_snow.png' },
  81: { name: 'pebbles', src: '/assets/tiles/pebbles.png' },
  82: { name: 'permasnow', src: '/assets/tiles/permasnow.png' },
  83: { name: 'quartzite cliff', src: '/assets/tiles/quartzite_cliff.png' },
  84: { name: 'quartzite floor', src: '/assets/tiles/quartzite_floor.png' },
  85: { name: 'quartzite tile', src: '/assets/tiles/quartzite_tile.png' },
  86: { name: 'sand ash', src: '/assets/tiles/sand_ash.png' },
  87: { name: 'sand orange', src: '/assets/tiles/sand_orange.png' },
  88: { name: 'sand white', src: '/assets/tiles/sand_white.png' },
  89: { name: 'sand', src: '/assets/tiles/sand.png' },
  90: { name: 'savannah', src: '/assets/tiles/savannah.png' },
  91: { name: 'shallowwater', src: '/assets/tiles/shallowwater.png' },
  92: { name: 'snow', src: '/assets/tiles/snow.png' },
  93: { name: 'stone tile', src: '/assets/tiles/stone_tile.png' },
  94: { name: 'swamp grass mar', src: '/assets/tiles/swamp_grass_mar.png' },
  95: { name: 'swamp grass nov', src: '/assets/tiles/swamp_grass_nov.png' },
  96: { name: 'swamp grass oct', src: '/assets/tiles/swamp_grass_oct.png' },
  97: { name: 'swamp grass sep', src: '/assets/tiles/swamp_grass_sep.png' },
  98: { name: 'swamp grass snowy', src: '/assets/tiles/swamp_grass_snowy.png' },
  99: { name: 'taidra', src: '/assets/tiles/taidra.png' },
  100: { name: 'taiga', src: '/assets/tiles/taiga.png' },
  101: { name: 'thornfloor damp', src: '/assets/tiles/thornfloor_damp.png' },
  102: { name: 'thornfloor dry', src: '/assets/tiles/thornfloor_dry.png' },
  103: { name: 'thornfloor snowy', src: '/assets/tiles/thornfloor_snowy.png' },
  104: { name: 'thornfloor', src: '/assets/tiles/thornfloor.png' },
  105: { name: 'tundra snowy', src: '/assets/tiles/tundra_snowy.png' },
  106: { name: 'tundra', src: '/assets/tiles/tundra.png' },
  107: { name: 'water', src: '/assets/tiles/water.png' },
  108: { name: 'wood tile', src: '/assets/tiles/wood_tile.png' },
  109: { name: 'wood wall', src: '/assets/tiles/wood_wall.png' },
  110: { name: 'woodpath snowy', src: '/assets/tiles/woodpath_snowy.png' },
  111: { name: 'woodpath', src: '/assets/tiles/woodpath.png' },
  112: { name: 'woodpath2', src: '/assets/tiles/woodpath2.png' },
  113: { name: 'yellow grass', src: '/assets/tiles/yellow_grass.png' },
};

export default TILE_TYPES;
