[project]
name = "signrpg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eventlet>=0.40.4",
    "flask-cors>=6.0.2",
    "flask-socketio>=5.6.0",
    "flask>=3.1.2",
    "mediapipe>=0.10.32",
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.92",
    "tensorflow>=2.20.0",
]
